### ISSUE TITLE
Enforce at least Maven 3.1.0 for all child projects

### ISSUE THREAD

**Issue by mkordas** [jcabi/jcabi-parent#51]
Due to bug in Maven, `qulice-maven-plugin` with Maven < `3.1.0` fails with NPE:
```
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
    at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
```
Maven `3.0.4` still remains default version for majority of Linux installations and is bundled with IntelliJ.

Let's add requirement to parent, that minimal Maven version to use is `3.1.0`.

Detailed stacktrace:
```
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
    at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.NullPointerException
    at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromChildren(CollectionConverter.java:157)
    at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:112)
    at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:289)
    at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:161)
    at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:567)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:529)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    ... 16 more
```

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmarkov** [comment]
@mkordas thanks a lot for reporting, **15 mins** added to your acc, pmt ID `56b2f9e0422cc6543a000035`

**Comment by dmarkov** [comment]
@amihaiemil could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by amihaiemil** [comment]
@dmarkov I created PR with id  #53 for this issue.

**Comment by dmarkov** [comment]
> @dmarkov I created PR with id  #53 for this issue.

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov The PR for this has been merged and closed successfully.

**Comment by mkordas** [comment]
@amihaiemil you should have asked me to close the issue

**Comment by amihaiemil** [comment]
@mkordas I thought I should wait for the PR to be deployed. My apologies, will do in the future.

**Comment by amihaiemil** [comment]
@dmarkov This issue was closed.

**Comment by dmarkov** [comment]
> @dmarkov The PR for this has been merged and closed successfully.

@amihaiemil OK

**Comment by amihaiemil** [comment]
@dmarkov I haven't received payment for this yet. Is there something else I should do?

**Comment by amihaiemil** [comment]
@dmarkov ping

**Comment by amihaiemil** [comment]
@dmarkov Can you give feedback here? Thanks.

**Comment by dmarkov** [comment]
> @dmarkov This issue was closed.

@amihaiemil thanks

**Comment by dmarkov** [comment]
@amihaiemil **30 mins** added to your account (payment number `AP-7EF141025M467294T`), many thanks for your contribution! 170 hours and 18 mins spent here.... +30 added to your rating, current score is: [+60](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
> @dmarkov I haven't received payment for this yet. Is there something else I should do? 

@amihaiemil paid already

**Comment by dmarkov** [comment]
> @dmarkov ping

@amihaiemil yes, I'm here. just be patient, we don't pay immediately (2-3 days are needed)

**Comment by dmarkov** [comment]
> @dmarkov Can you give feedback here? Thanks.

@amihaiemil you don't need to ask me multiple times, it doesn't make things faster. just one question is enough, I will answer it sooner or later. thanks

**Comment by amihaiemil** [comment]
@dmarkov Thanks for the info, I will know in the future.

**Comment by dmarkov** [comment]
> @dmarkov Thanks for the info, I will know in the future.

@amihaiemil OK
